### 向量的基本操作

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 创建向量
vector1 = np.array([1, 2, 3])
vector2 = np.array([3, 2, 1])

In [3]:
# 向量加法
vector_add = vector1 + vector2
# 向量减法
vector_sub = vector1 - vector2
# 向量数乘
vector_mul = 2 * vector1
# 向量点乘
vector_dot = np.dot(vector1, vector2)
# 向量叉乘
vector_cross = np.cross(vector1, vector2)
# 向量模
vector_norm = np.linalg.norm(vector1)
# 向量夹角
# cosθ = (a·b) / (|a|*|b|)
vector_angle = np.arccos(vector_dot / (vector_norm * vector_norm))

# 输出结果
print('vector1 + vector2 = ', vector_add)
print('vector1 - vector2 = ', vector_sub)
print('2 * vector1 = ', vector_mul)
print('vector1 · vector2 = ', vector_dot)
print('vector1 × vector2 = ', vector_cross)
print('|vector1| = ', vector_norm)
print('θ = ', vector_angle)

vector1 + vector2 =  [4 4 4]
vector1 - vector2 =  [-2  0  2]
2 * vector1 =  [2 4 6]
vector1 · vector2 =  10
vector1 × vector2 =  [-4  8 -4]
|vector1| =  3.7416573867739413
θ =  0.7751933733103613


### 矩阵基本操作

In [4]:
# 创建矩阵，这里使用方阵
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('matrix1 = \n', matrix1)
print('matrix2 = \n', matrix2)

matrix1 = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix2 = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# 矩阵加法
matrix_add = matrix1 + matrix2
# 矩阵减法
matrix_sub = matrix1 - matrix2
# 矩阵数乘
matrix_mul = 2 * matrix1
# 矩阵点乘
# matrix_dot = matrix1 @ matrix2
matrix_dot = np.dot(matrix1, matrix2)
# 矩阵转置
matrix_transpose = matrix1.T
# 矩阵行列式
matrix_det = np.linalg.det(matrix1)
# 矩阵逆（矩阵不满秩也会返回值）
matrix_inv = np.linalg.inv(matrix1)

# 输出结果
print('matrix1 + matrix2 = \n', matrix_add)
print('matrix1 - matrix2 = \n', matrix_sub)
print('2 * matrix1 = \n', matrix_mul)
print('matrix1 · matrix2 = \n', matrix_dot)
print('matrix1.T = \n', matrix_transpose)
print('|matrix1| = ', matrix_det)
print('matrix1^-1 = \n', matrix_inv)

matrix1 + matrix2 = 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
matrix1 - matrix2 = 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
2 * matrix1 = 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
matrix1 · matrix2 = 
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
matrix1.T = 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
|matrix1| =  6.66133814775094e-16
matrix1^-1 = 
 [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
